package by.bsuir.domain.command;

public enum Commands {
    SIGN_IN,
    SIGN_UP,
    GET_USER_BY_ID,

    //
    //
    ADD_NEW_USER,
    UPDATE_USER_PASSWORD,
    GET_ALL_USERS,
    UPDATE_USER,
    DELETE_USER,
    //
    ADD_NEW_SEGMENT,
    DELETE_SEGMENT,
    GET_ALL_SEGMENT,
    UPDATE_SEGMENT,
    //
    ADD_NEW_COMPANY,
    UPDATE_COMPANY,
    DELETE_COMPANY,
    GET_ALL_COMPANIES,


    GET_ALL_MARKED_COMPANIES,
    GET_ALL_NON_MARKED_COMPANIES

}
